stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Build"
    - mkdir build
    - touch build/test.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Test"
    - test -f build/test.txt
